version: '3.8'
services:
  backend:
    image: <your-dockerhub-username>/quotehub-backend
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
  frontend:
    image: <your-dockerhub-username>/quotehub-frontend
    ports:
      - "80:80"
    deploy:
      replicas: 1